image: node:5.10

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/
    - bower_components/

before_script:
  - npm config set spin false
  - npm config set cache-min 9999
  - npm install --prefer-offline

stages:
  - test
  - publish

test-ember-default:
  stage: test
  script:
    - ember try:one ember-default
  tags:
    - test

test-ember-lts-2.8:
  stage: test
  script:
    - ember try:one ember-lts-2.8
  tags:
    - test
  only:
    - master

test-ember-lts-2.12:
  stage: test
  script:
    - ember try:one ember-lts-2.12
  tags:
    - test
  only:
    - master

test-ember-release:
  stage: test
  script:
    - ember try:one ember-release
  tags:
    - test
  only:
    - master

test-ember-beta:
  stage: test
  script:
    - ember try:one ember-canary
  tags:
    - test
  only:
    - master

test-ember-beta:
  stage: test
  script:
    - ember try:one ember-beta
  tags:
    - test
  only:
    - master

publish:
  stage: publish
  script:
    - npm publish
  when: manual
  tags:
    - build
    - lvo-environment
